"""
Report formatter.

Generates a Markdown security report from scan results.
"""

import json
from datetime import datetime


SEVERITY_ICON = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🔵",
    "INFO": "⚪",
}


def generate_markdown(scan_result: dict) -> str:
    """Generate a Markdown security report."""
    server = scan_result.get("server_info", {})
    summary = scan_result.get("summary", {})
    findings = scan_result.get("findings", [])
    tools = scan_result.get("tools", [])

    lines = []
    lines.append("# MCP Security Audit Report")
    lines.append("")
    lines.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**Target:** {server.get('name', 'Unknown')} v{server.get('version', '?')}")
    lines.append(f"**Tools discovered:** {len(tools)}")
    lines.append(f"**Checks run:** {scan_result.get('checks_total', 0)}")
    lines.append(f"**Checks passed:** {scan_result.get('checks_passed', 0)}")
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        count = summary.get(sev, 0)
        if count > 0:
            lines.append(f"| {SEVERITY_ICON[sev]} {sev} | {count} |")
    lines.append(f"| **TOTAL** | **{summary.get('total', 0)}** |")
    lines.append("")

    # Risk assessment
    crit = summary.get("CRITICAL", 0)
    high = summary.get("HIGH", 0)
    if crit > 0:
        lines.append("> **RISK: CRITICAL.** This server has critical vulnerabilities that "
                      "allow unauthenticated access, remote code execution, or secret exposure. "
                      "Do not deploy in production without remediation.")
    elif high > 0:
        lines.append("> **RISK: HIGH.** This server has significant security gaps. "
                      "Remediate high-severity findings before production use.")
    else:
        lines.append("> **RISK: MODERATE.** No critical or high findings. Review medium/low "
                      "findings and harden as appropriate.")
    lines.append("")

    # Findings
    lines.append("## Findings")
    lines.append("")

    for i, finding in enumerate(findings, 1):
        icon = SEVERITY_ICON.get(finding.severity.value, "")
        lines.append(f"### {i}. {icon} [{finding.check_id}] {finding.title}")
        lines.append("")
        lines.append(f"**Severity:** {finding.severity.value}")
        if finding.tool_name:
            lines.append(f"**Tool:** `{finding.tool_name}`")
        lines.append("")
        lines.append(finding.description)
        lines.append("")

        if finding.evidence:
            lines.append(f"**Evidence:** {finding.evidence}")
            lines.append("")

        if finding.remediation:
            lines.append(f"**Remediation:** {finding.remediation}")
            lines.append("")

        if finding.cve_refs:
            lines.append(f"**Related CVEs:** {', '.join(finding.cve_refs)}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Tool inventory
    lines.append("## Tool Inventory")
    lines.append("")
    lines.append("| Tool | Input Parameters | Has Required Fields |")
    lines.append("|------|-----------------|-------------------|")
    for tool in tools:
        name = tool.get("name", "?")
        schema = tool.get("inputSchema", {})
        props = list(schema.get("properties", {}).keys())
        required = schema.get("required", [])
        lines.append(f"| `{name}` | {', '.join(props) or 'none'} | {'Yes' if required else 'No'} |")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by [MCP Security Auditor](https://github.com/Gabyc5/mcp-security-auditor)*")

    return "\n".join(lines)


def generate_json(scan_result: dict) -> str:
    """Generate a JSON report for automation."""
    output = {
        "timestamp": datetime.now().isoformat(),
        "server": scan_result.get("server_info", {}),
        "summary": scan_result.get("summary", {}),
        "checks_passed": scan_result.get("checks_passed", 0),
        "checks_total": scan_result.get("checks_total", 0),
        "findings": [
            {
                "check_id": f.check_id,
                "title": f.title,
                "severity": f.severity.value,
                "description": f.description,
                "evidence": f.evidence,
                "remediation": f.remediation,
                "tool_name": f.tool_name,
                "cve_refs": f.cve_refs,
            }
            for f in scan_result.get("findings", [])
        ],
        "tools": [
            {"name": t.get("name"), "description": t.get("description", "")[:100]}
            for t in scan_result.get("tools", [])
        ],
    }
    return json.dumps(output, indent=2)
